### ISSUE TITLE
Error on build_report

### ISSUE THREAD

**Issue by brittanyhowell** [brwnj/covviz#15]
Howdy, 

I tried to test covviz and ran into errors when building the final report - It reported that there were no traces on any of the chromosomes (see below) but I did check NF-indexcov.bed.gz and there were indeed values for each of the samples in a standard looking bed3+. 
I'm not sure what else could be wrong, do you have any advice? 

Many thanks, 

  ```
covviz --min-samples 8 --sex-chroms X,Y --exclude '^GL|^hs|EBV$|M$|MT$|^NC|_random$|Un_|^HLA\-|_alt$|hap\d+$'         --z-threshold 3.5 --distance-threshold 150000         --slop 500000 --ped NF-indexcov.ped  --skip-norm NF-indexcov.bed.gz

Command exit status:
  1

Command output:
  (empty)

Command error:
  [INFO] parsing bed file (NF-indexcov.bed.gz)
  [INFO] plotting 2 traces on chrom chr1
  [INFO] plotting 2 traces on chrom chr10
  [INFO] plotting 2 traces on chrom chr11
```

**Comment by brwnj** [comment]
I'm happy to check it out, but would need access to your bed and ped files.

**Comment by brittanyhowell** [comment]
Thanks so much! 
I've put relevant files here: https://github.com/brittanyhowell/view_regions_covviz
It did happen to build when provided with one or ten CRAMs, but failed with two - I'm not what in the CRAMs is causing the failure.

**Comment by brwnj** [comment]
can you give that a test? i updated and tested the python and js on your files, but only tested nextflow on my local indexes.

**Comment by brittanyhowell** [comment]
Hi sorry, having trouble running with updates. 
I ran it with nextflow and had a conflict:
`Unable to find image 'brwnj/covviz:v1.3.1' locally`
`docker: Error response from daemon: manifest for brwnj/covviz:v1.3.1 not found: manifest unknown: manifest unknown.`

I tried pulling from docker (docker pull brwnj/covviz) because I thought the version might not be updating or there might be something mismatching about tags. But my knowledge of docker is letting me down here. 

Is there a different way I should be testing this - sorry, thanks again.

**Comment by brwnj** [comment]
issues associated with docker hub. i've verified the upload and tested the cloud version. hopefully you can test that again from your side.

**Comment by brittanyhowell** [comment]
It built! 
Still did not see anything in the html however. 
After some inspection of the html, I found that toggling the chr menu causes the proportions covered plot to show, and changing chr shows different plots. But the number in the chromosome box does not change. 
And no other plots are currently visible as far as I can tell.

**Comment by brwnj** [comment]
k, decent news. can you push these new files to your repo that you shared with me before?

**Comment by brittanyhowell** [comment]
Absolutely - full results dir is here: https://github.com/brittanyhowell/view_regions_covviz/tree/master/test-131/results-complete/

**Comment by brwnj** [comment]
thanks for your patience on this one.

it's unclear why your local repo of covviz is not being updated by nextflow when using `-latest`. the current revision (now after updating license info) is e49ac5ef5d.

```
nextflow run brwnj/covviz -latest -profile docker --indexes 'data/indexes/*.crai' --fai data/g1k_v37_decoy.fa.fai
N E X T F L O W  ~  version 20.10.0
Pulling brwnj/covviz ...
Already-up-to-date
Launching `brwnj/covviz` [festering_shaw] - revision: e49ac5ef5d [master]
```

Generates: [covviz_report.html.gz](https://github.com/brwnj/covviz/files/5979189/covviz_report.html.gz)

**Comment by brittanyhowell** [comment]
Thank you so much for your persistence! 

Good news - it ran! With no errors, and built a html which opened and displayed all plots! 
Bad news - the results were a bit questionable. 
I've documented the strange results [in a README here](https://github.com/brittanyhowell/view_regions_covviz/tree/master/test-e49ac5ef5d). 

I don't think the errors are a result of compromosed CRAMs - I did check the CRAMs and visualised in IGV and they seem normal, but covviz is reporting no reads or an abundance of reads and I am not quite sure why. 

Does this look fishy to you?

**Comment by brwnj** [comment]
Yes, these results are strange! The coverage reports coming from indexcov
clearly have something going on with them - chromosomes partially counted,
missing, or otherwise - things aren’t looking normal.

Consider recreating a few of the cram indexes and trying again. Bad indexes
are unfortunately pretty common.

**Comment by brittanyhowell** [comment]
It worked. 
Everything worked. 
The plots are beautiful.
Incidentally - I tried to edit a PED file and run covviz without nf to see if that worked too and well. It did. 
Everything is perfect.
Thank you so, so much for this, it's made my manual CNV dredging so much nicer!

One last question - how many samples do you think this could take at once? I intend on browsing quite a few..

Seriously though your help has been invaluable.

**Comment by brwnj** [comment]
I've run it on 1kg data (https://home.chpc.utah.edu/~u6022494/covviz/1000G_2504_high_cov/covviz_report.html) and it mostly works. We've since updated the normalization method for cram indexes, so yours may look a bit cleaner than this.
