### ISSUE TITLE
Unable to find image 'brwnj/covviz:v1.3.2' locally

### ISSUE THREAD

**Issue by robertwhbaldwin** [brwnj/covviz#16]
I'm getting an error when trying to run covviz with nextflow. I'm new to docker/nextflow and was hoping that someone would be able to identify the problem as I followed all the instructions on the covviz page. thanks - Robert 

./nextflow run brwnj/covviz -profile docker --exclude --sex --indexes '/media/robert/External_Drive/BAMS/*.bai' --fai /home/robert/assembly/GCF_014851395.1_ASM1485139v1_genomic.fa.fai
N E X T F L O W  ~  version 21.04.2
Launching `brwnj/covviz` [focused_wilson] - revision: 614537da34 [master]

====================================================================
covviz - find large, coverage-based variations on chromosomes 
====================================================================

#### Homepage / Documentation
https://github.com/brwnj/covviz
#### Authors
Joe Brown <brwnjm@gmail.com>

====================================================================

Alignment indexes            --indexes          : /media/robert/External_Drive/BAMS/*.bai
Reference index              --fai              : /home/robert/assembly/GCF_014851395.1_ASM1485139v1_genomic.fa.fai
Sex chromosomes              --sexchroms        : X,Y
Excluded chroms              --exclude          : true
Z threshold                  --zthreshold       : 3.5
Distance threshold           --distancethreshold: 150000
Significant region slop      --slop             : 500000

====================================================================

executor >  local (1)
[b1/5a449d] process > run_indexcov [  0%] 0 of 1
executor >  local (1)
[b1/5a449d] process > run_indexcov [100%] 1 of 1, failed: 1 ✘
[-        ] process > merge_peds   -
[-        ] process > build_report -
Error executing process > 'run_indexcov'

Caused by:
  Process `run_indexcov` terminated with an error exit status (125)

Command executed:

  goleft indexcov --sex X,Y --excludepatt "true" --directory NF --fai GCF_014851395.1_ASM1485139v1_genomic.fa.fai RHF05438.bam.bai RHF05338.bam.bai RHF05342.bam.bai RHF05347.bam.bai RHF05358.bam.bai RHF05397.bam.bai RHF05432.bam.bai RHF05301.bam.bai G0620_M02.bam.bai RHF05302.bam.bai RHF05350.bam.bai G0319-20-B0074.bam.bai G0319-20-B0115.bam.bai G0319-20-B0117.bam.bai G0520-1-G359.bam.bai RHF05357.bam.bai RHF05398.bam.bai RHF05440.bam.bai RHF05444.bam.bai RHF05462.bam.bai RHF05464.bam.bai RHF05453.bam.bai RHF05431.bam.bai RHF05421.bam.bai RHF05452.bam.bai
  mv NF/* .

Command exit status:
  125

Command output:
  (empty)

Command error:
  Unable to find image 'brwnj/covviz:v1.3.2' locally
  docker: Error response from daemon: manifest for brwnj/covviz:v1.3.2 not found: manifest unknown: manifest unknown.
  See 'docker run --help'.

Work dir:
  /home/robert/tools/work/b1/5a449d420115e8ca3bd6be1f35bae0

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

**Comment by robertwhbaldwin** [comment]
I think the problem is related to the docker image tag. shouldn't it be looking for covviz:latest? 

When I run sudo docker images there's no image v1.3.2. 


REPOSITORY                TAG       IMAGE ID       CREATED        SIZE
brwnj/covviz              latest    b90835069977   2 months ago   1.37GB
hello-world               latest    d1165f221234   4 months ago   13.3kB
aakechin/ngs-primerplex   native    7df8a7df6a5f   4 months ago   680MB
brentp/smoove             latest    bdf809472b6a   8 months ago   2.68GB



UPDATE: i updated the image tag to read v1.3.2 instead of latest and it ran

**Comment by brwnj** [comment]
fixed it. i pushed to latest but didn't include the 1.3.2 tag. should work now
