### ISSUE TITLE
miscellaneous

### ISSUE THREAD

**Issue by brentp** [brwnj/covviz#4]
in getting this to run on non-indexcov output I found a few issues:

1. it requires the .roc output from indexcov which is pretty specific. this can be calculated directly from the bed files. 
2. it requires the .ped output from indexcov. this should be optional. and many values can be 
3. it requires a gff which defaults to $gff. all of the parameters are defaulting to the string literal `$gff` or `$roc`. this makes it odd to call from the command-line. for example it looks for `$sex_ chroms` so it's very hard to call from the command-line.
4. there is no information on a sensible value for --z-threshold or --distance or --slop. I don't know what the latter 2 of those are for.
5. all instances in the javascript of `$(...)` are left escaped as `\$(...)`. 

I will work on some of these, but I wanted to document them here.

**Comment by brwnj** [comment]
We've addressed all of these issues by making the python code a separate package and CLI.

1. A .roc file is no longer needed and is calculated from the bed input
2. .ped is optional
3. A .gff is optional
4. The readme and CLI documentation has been improved
5. The implementation of the js has been changed such that this is no longer an issue
